#! /usr/bin/env bash

set +x

rebuild_home() {
  nix build .#homeConfigurations.marcinwadon.activationPackage
  activateHM
}

activateHM() {
  rm -rf ~/.config/secrets
  HOME_MANAGER_BACKUP_EXT=bak result/activate
}

case $1 in
  "home")
    rebuild_home;;
  "darwin")
    darwin-rebuild switch --flake .;;
  "update-fish")
    fish -c fish_update_completions;;
  *)
    echo "Usage: $0 {home|darwin|update-fish}"
    echo "  home      - rebuild home-manager configuration"
    echo "  darwin    - rebuild darwin system configuration" 
    echo "  update-fish - update fish completions";;
esac
