#! /usr/bin/env bash

set +x

rebuild_home() {
  nix build .#homeConfigurations.marcinwadon.activationPackage
  activateHM
}

activateHM() {
  rm -rf ~/.config/secrets
  HOME_MANAGER_BACKUP_EXT=bak result/activate
}

case $1 in
  "home")
    rebuild_home;;
  "darwin")
    darwin-rebuild switch --flake .;;
  "update-fish")
    fish -c fish_update_completions;;
  "update-flakes")
    nix flake update;;
  *)
    echo "Usage: $0 {home|darwin|update-fish|update-flakes}"
    echo "  home        - rebuild home-manager configuration"
    echo "  darwin      - rebuild darwin system configuration"
    echo "  update-fish - update fish completions"
    echo "  update-flakes - update all flake inputs";;
esac
